config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :articles
  resources :reviews

  get 'zespol', to: 'pages#zespol'
  get 'zespol/grzegorz-szczeblewski', to: 'pages#grzegorz_szczeblewski'
  get 'zespol/elzbieta-walczak', to: 'pages#ela_walczak'
  get 'zespol/donata-grodek', to: 'pages#donata_grodek'
  get 'zespol/kamila-czarnuch', to: 'pages#kamila_czarnuch'
  get 'zespol/dominika-lisiecka', to: 'pages#dominika_lisiecka'
  get 'zespol/aleksandra-stepien', to: 'pages#aleksandra_stepien'
  get 'zespol/marta-mlodzianowska', to: 'pages#marta_mlodzianowska'
  get 'zespol/tadeusz-kurpisz', to: 'pages#tadeusz_kurpisz'
  get 'zespol/katarzyna-wojtczak', to: 'pages#katarzyna_wojtczak'
  get 'zespol/robert-krzyzanowski', to: 'pages#robert_krzyzanowski'
  get 'zespol/malgorzata-radziwolek', to: 'pages#malgorzata_radziwolek'
  get 'zespol/magdalena-luczyk', to: 'pages#magdalena_luczyk'
  get 'zespol/anetta-idziorek', to: 'pages#anetta_idziorek'
  get 'zespol/tamara-pieczerer', to: 'pages#tamara_pieczerer'
  get 'zespol/katarzyna-maria-zawadzka', to: 'pages#katarzyna_zawadzka'
  get 'zespol/marta-moszko', to: 'pages#marta_moszko'
  get 'zespol/edyta-konopacka', to: 'pages#edyta_konopacka'
  get 'zespol/joanna-krezelewska', to: 'pages#joanna_krezelewska'
  get 'oferta', to: 'pages#oferta'
  get 'oferta/konsultacja', to: 'pages#konsultacja'
  get 'oferta/terapia', to: 'pages#terapia'
  get 'oferta/pomoc-kryzys', to: 'pages#pomoc_kryzys'
  get 'oferta/uzaleznienia', to: 'pages#uzaleznienia'
  get 'oferta/terapia-par', to: 'pages#terapia_par'
  get 'gabinety', to: 'pages#gabinety'
  get 'blog', to: 'pages#articles'
  get 'kontakt', to: 'pages#kontakt'
  get 'admin', to: 'pages#admin'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :rich_body
  has_many_attached :photos
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:  %i[ index show ]
  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_path, notice: 'Article was successfully destroyed.'
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :tagline, :rich_body, photos: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]
  before_action :authenticate_user!, only:  %i[ admin ]

  def home
    @reviews = Review.all
  end

  def zespol
  end

  def grzegorz_szczeblewski
  end

  def ela_walczak
  end

  def kamila_czarnuch
  end

  def malgorzata_radziwolek
  end

  def services
  end

  def konsultacja
  end

  def terapia
  end

  def gabinety
  end

  def admin
    @reviews = Review.all
    @articles = Article.all
    # @new_review = Review.new
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to reviews_path, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to reviews_path
  end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    redirect_to reviews_path, notice: 'Review was successfully destroyed.'
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :tagline %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-inputs">
    <%= f.rich_text_area :rich_body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<section class="banner-pages">
  <div class="banner-pages-title">
    <h1>BLOG</h1>
  </div>
</section>

<section>
  <div class="container">
    <!-- <p id="notice"><%= notice %></p> -->
    <div class="articles-items">
      <% @articles.each do |article| %>
        <div class="article-card hover-content shadow-hover">
          <% if article.photos.attached? %>
            <%= cl_image_tag article.photos[0].key, height: 300, width: 400, crop: :fill, class: "article-card__photo" %>
          <% end %>
          <div class=article-card__title>
            <h2><%= article.title %></h2>
            <%= link_to 'Show', article, class: "btn-cards" %>
            <!-- <p><%= article.tagline %></p> -->
          </div>
          <% if user_signed_in? %>
          <div class="article-card__links">
            <%= link_to 'Show | ', article %>
            <%= link_to 'Edit | ', edit_article_path(article) %>
            <%= link_to 'Destroy | ', article, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to 'New Article ', new_article_path %>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/pages/grzegorz_szczeblewski.html.erb
<section class="banner-pages">
  <div class="banner-pages-title">
    <h1>Grzegorz Szczeblewski</h1>
    <p>Psycholog - Psychoterapeuta</p>
  </div>
</section>

<section class="container">
  <div class="people-about" id="grzegorz">
    <div class="people-about__img">
      <img src="/assets/Grzegorz_Szczeblewski.jpg" alt="Grzegorz Szczeblewski - psycholog, psychoterapeuta">
    </div>
    <div class=people-about__text>
      <p>Jestem absolwentem Szkoły Wyższej Psychologii Społecznej  Uniwersytetu Humanistycznospołecznego w Sopocie.
        Ukończyłem studia magisterskie na Wydziale Psychologii (specjalizacja kliniczna i zdrowia) oraz Szkołę Psychoterapii Osób  z Problemem Uzależnienia w Laboratorium Psychoedukacji. Aktualnie jestem
        w trakcie szkolenia w Szkole Psychoterapii Psychodynamicznej  w Krakowskim Centrum Psychodynamicznym.</p>
      <p>Doświadczenie jako psycholog zdobywałem m.in. w Szpitalu dla Nerwowo i Psychicznie Chorych w Starogardzie Gdańskim,
        Wojewódzkim Szpitalu Psychiatrycznym w Gdańsku, Wojewódzkim Centrum Onkologii w Gdańsku, Centrum Psychoterapii
        i Leczenia Uzależnień ANON w Koszalinie oraz Środkowopomorskim Centrum Zdrowia Psychicznego MEDISON w Koszalinie.</p>
        <p>Nieustannie rozwijam się i doskonalę swoje kompetencje uczestnicząc w kursach specjalistycznych. Moja praca poddawana
        jest stałej superwizji.</p>
      <p>Jestem członkiem Polskiego Towarzystwa Psychologicznego oraz Polskiego Towarzystwa Psychoterapii Psychodynamicznej.</p>
    </div>
  </div>
</section>

<section class="container">
  <div class="grey-box">
    <p><em>W kontakcie z drugim człowiekiem ważne jest dla mnie nawiązanie szczerej i pełnej empatii relacji. Towarzyszę swoim klientom w kłopotach i kryzysach, które nie pozwalają im w pełni cieszyć się życiem. Odnajduję prawdziwą radość i satysfakcję pomagając w rozwoju oraz budowaniu nowych rozwiązań. Psychologia jest moją pasją a, praca z ludźmi moim powołaniem.</em></p>
  </div>
</section>

<!-- jak pracuje section-->
<section>
  <div class="container">
    <div class="section-titles">
      <h2>JAK PRACUJĘ</h2>
      <hr />
    </div>
    <div>
      <p>Pracuję w podejściu psychodynamicznym, które zostało opracowane na podstawie dorobku współczesnej psychiatrii oraz uznanych koncepcji psychoanalitycznych. Psychoterapia psychodynamiczna toczy się w oparciu o relację terapeutyczną czyli więź, jaka rozwija się pomiędzy pacjentem a terapeutą w trakcie trwania leczenia.
      <br>
      <br>
      Psychoterapeuta psychodynamiczny nie daje dobrych rad lecz stara się pomóc pacjentowi w lepszym rozumieniu jego własnych myśli, zachowań, pragnień i uczuć. W tym procesie rolą psychoterapeuty jest towarzyszenie człowiekowi w poszukiwaniu lepszych sposobów rozwiązania jego problemów niż te, które do tej pory stosował, a także wskazywanie tego, czego sam nie mógł dostrzec.
      <br>
      <br>
      Pacjent podczas terapii w gabinecie staje na drodze do lepszego poznania i zrozumienia siebie oraz wzmocnienia poczucia własnej wartości. Psychoterapia ma pomóc w przeżywaniu życia głębiej, bardziej świadomie, w doświadczaniu w pełni jego blasków i cieni.</p>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="section-titles">
      <h2>W czym mogę pomóc?</h2>
      <hr />
    </div>
    <div class="offer-icons">
      <div class="cards">
        <%= link_to oferta_konsultacja_path do %>
          <div class="card shadow-cards">
            <img src="/assets/icon-konsultacja.jpg" alt="Konsultacja Psychologiczna">
            <div class="card-info fade-in">
              <h2>Konsultacja<br>Psychologiczna</h2>
            </div>
          </div>
        <% end %>
        <%= link_to oferta_terapia_path do %>
          <div class="card shadow-cards">
            <img src="/assets/icon-terapia.jpg" alt="Psychoterapia Indywidualna">
            <div class="card-info fade-in">
              <h2>Psychoterapia <br>Indywidualna</h2>
            </div>
          </div>
        <% end %>
        <%= link_to oferta_pomoc_kryzys_path do %>
          <div class="card shadow-cards">
            <img src="/assets/icon-kryzys.jpg" alt="pomoc w sytuacji kryzysowej">
            <div class="card-info fade-in">
              <h2>Pomoc w sytuacji<br>kryzysowej</h2>
            </div>
          </div>
        <% end %>
        <%= link_to oferta_terapia_par_path do %>
          <div class="card shadow-cards">
            <img src="/assets/icon-pary.png" alt="Terapia Par">
            <div class="card-info fade-in">
              <h2>Terapia par</h2>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="section-titles">
      <h2>CENNIK</h2>
      <hr />
    </div>
    <table id="cennik">
      <tr>
        <th>Usługa</th>
        <th>Cena</th>
      </tr>
      <tr>
        <td>Konsultacja psychologiczna</td>
        <td>150 zł / 50 min. </td>
      </tr>
      <tr>
        <td>Psychoterapia indywidualna </td>
        <td>150 zł / 50 min. </td>
      </tr>
      <tr>
        <td>Interwencja w sytuacji kryzysu </td>
        <td>160 zł / 50 min. </td>
      </tr>
      <tr>
        <td>Terapia Par </td>
        <td>250 zł / 1.5 h </td>
      </tr>
    </table>
  </div>
</section>

<section class="team-contact">
  <div class="container">
    <div class="section-titles">
      <h2>Umów wizytę</h2>
      <hr />
    </div>
    <div class="team-contact__grid">
      <div class="team-contact__grid-left">
        <div class="contact-way shadow-cards">
          <i class="fas fa-phone"></i>
          <p><a href="tel://+48663061717">Grzegorz Szczeblewski<br>+48663061717</a></p>
        </div>
        <div class="contact-way shadow-cards">
          <i class="far fa-envelope"></i>
          <p><a href="mailto:gabinet@psycho-terapeutyczny.pl">gabinet@psycho-terapeutyczny.pl</a></p>
        </div>
        <div class="contact-way shadow-cards">
          <i class="far fa-map"></i>
          <p><strong>Adres:</strong></p>
          <p><a href="https://goo.gl/maps/dHAgUrewkDeaVZkb8">Centrum Psychoterapii<br>Dębowa 29<br>75-900 Koszalin</a></p>
        </div>
      </div>
      <div class="team-contact__grid-right">
        <p>Zapraszamy na wizyty po wcześniejszej rejestracji telefonicznej bądź konsultacji mailowej.</p>
        <p>W razie nie odbierania telefonu, prosimy o wiadomość SMS, a oddzwonimy.</p>
        <div class="map-responsive">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d583.697936139031!2d16.22568482930438!3d54.183763998760234!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4701cd34b152c0f1%3A0xc65cc48d61b76476!2sCentrum%20Psychoterapii%20psycho-terapeutyczny.pl!5e0!3m2!1sen!2suk!4v1627473859742!5m2!1sen!2suk" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/konsultacja.html.erb
<section class="banner-pages">
  <div class="banner-pages-title">
     <h1>Konsultacja Psychologiczna</h1>
  </div>
</section>

<section>
  <div class="oferta-subpages container">
    <div class="oferta-subpages_text text-center">
      <p>
        Dzięki konsultacji psychologicznej możliwe jest wstępne rozpoznanie sytuacji życiowej pacjenta oraz określenie jego problemów. Z tego względu stanowi ona stanowią wstęp do dalszego postępowania oraz terapii.
      </p>
      <h2>Ta forma pomocy sprawdzi się gdy:</h2>
      <ul>
        <li>znalazłeś się w sytuacji, z którą nie potrafisz sobie poradzić i potrzebujesz wsparcia</li>
        <li>masz trudną sytuację i chcesz się zastanowić, co dalej</li>
        <li>czujesz, że potrzebujesz pomocy, ale nie wiesz jaka forma będzie dla Ciebie najkorzystniejsza, tzn. czy wybrać psychoterapię indywidualną, grupową czy może wcześniej udać się do lekarza psychiatry</li>
        <li>czujesz, że chciałbyś coś zmienić w swoim życiu, ale nie potrafisz tego nazwać i nie wiesz od czego zacząć.</li>
      </ul>
    </div>
    <div class="oferta-subpages_photo">
      <img src="/assets/konsultacja.jpg" alt="Psycholog - Konsultacja Psychologiczna">
    </div>
  </div>
</section>

<section class="section-subpages">
  <div class="container">
    <div class=" oferta-subpages_text text-center">
      <h2>Kto może skorzystać z konsultacji psychologicznych?</h2>
      <p>Najprościej ujmując każdy, kto uważa, że jej potrzebuje. Rozmowa ze specjalistą pozwala na omówienie wszelkich problemów emocjonalnych, rodzinnych i życiowych.
      Może stanowić pierwszy krok na drodze do rozpoznania problemów oraz ich rozwiązania. Jest to jednorazowa usługa, która ma na celu poradę w zmaganiu się z problemami,
      jednak pełne rozpoznanie może wymagać od trzech do pięciu spotkań i ma na celu postanowienie diagnozy. Dzięki której pacjent może zostać poddany leczeniu.</p>
      <br>
      <h2>Jakie są przykładowe wskazania do skorzystania z konsultacji psychologicznej?</h2>
      <p>Do najczęstszych przyczyn należą problemy z kontrolowaniem emocji, utrzymujący się zły nastrój, stresy, zaburzenia lękowe, problemy ze snem, trudności związane z relacjami interpersonalnymi,
      wypalenie zawodowe, kłopoty rodzinne lub zaburzenia emocjonalne. Powodem do skorzystania z pomocy specjalisty mogą być wszystkie problemy, które sprawiają, że pacjent odczuwa potrzebę wsparcia.</p>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="oferta-subpages">
      <div class="oferta-subpages__people">
        <div class="section-titles">
          <h3>terapeuci:</h3>
          <hr/>
        </div>
        <%= link_to zespol_donata_grodek_path do %>
          <h4><i class="fas fa-chevron-right"></i>Donata Grodek</h4>
        <%end%>
        <%= link_to zespol_grzegorz_szczeblewski_path do %>
          <h4><i class="fas fa-chevron-right"></i>Grzegorz Szczeblewski</h4>
        <%end%>
        <%= link_to zespol_elzbieta_walczak_path do %>
          <h4><i class="fas fa-chevron-right"></i>Elżbieta Walczak</h4>
        <%end%>
        <%= link_to zespol_kamila_czarnuch_path do %>
          <h4><i class="fas fa-chevron-right"></i>Kamila Czarnuch</h4>
        <%end%>
        <%= link_to zespol_aleksandra_stepien_path do %>
          <h4><i class="fas fa-chevron-right"></i>Aleksandra Stępień</h4>
        <%end%>
        <%= link_to zespol_marta_mlodzianowska_path do %>
          <h4><i class="fas fa-chevron-right"></i>Marta Młodzianowska</h4>
        <%end%>
        <%= link_to zespol_tadeusz_kurpisz_path do %>
          <h4><i class="fas fa-chevron-right"></i>Tadeusz Kurpisz</h4>
        <%end%>
        <%= link_to zespol_robert_krzyzanowski_path do %>
          <h4><i class="fas fa-chevron-right"></i>Robert Krzyżanowski</h4>
        <%end%>
        <%= link_to zespol_tadeusz_kurpisz_path do %>
          <h4><i class="fas fa-chevron-right"></i>Tadeusz Kurpisz</h4>
        <%end%>
        <%= link_to zespol_anetta_idziorek_path do %>
          <h4><i class="fas fa-chevron-right"></i>Anetta Idziorek</h4>
        <%end%>
        <%= link_to zespol_tamara_pieczerer_path do %>
          <h4><i class="fas fa-chevron-right"></i>Tamara Pieczerer</h4>
        <%end%>
        <%= link_to zespol_marta_moszko_path do %>
          <h4><i class="fas fa-chevron-right"></i>Marta Moszko</h4>
        <%end%>
        <%= link_to zespol_edyta_konopacka_path do %>
          <h4><i class="fas fa-chevron-right"></i>Edyta Konopacka-Ilkiewicz</h4>
        <%end%>
         <%= link_to zespol_joanna_krezelewska_path do %>
          <h4><i class="fas fa-chevron-right"></i>Joanna Krężelewska</h4>
        <%end%>
      </div>

      <div class="oferta-subpages__contact text-center">
        <%= render 'shared/kontakt-box' %>
      </div>
    </div>
  </div>
</section>

app/views/pages/uzaleznienia.html.erb
<section class="banner-pages">
  <div class="banner-pages-title">
     <h1>Pomoc w uzależnieniach</h1>
  </div>
</section>

<section>
  <div class="oferta-subpages container">
    <div class="oferta-subpages_text text-center">
      <p>Zapewniamy nowoczesne i kompleksowe leczenie osobom borykającym się z różnego rodzaju uzależnieniami, zarówno w zakresie substancji psychoaktywnych, jak i uzależnień behawioralnych. W leczeniu uzależnień niebywale istotne jest uwzględnienie indywidualnej historii danej osoby. Istnieje szereg czynników obciążających, które zwiększają ryzyko wystąpienia uzależnienia. Zalicza się do nich m.in. problemy rodzinne, nieporozumienia w bliskich relacjach, presję zawodową, kłopoty finansowe, wywodzenie się z rodziny, w której występuje wzorzec uzależnienia/współuzależnienia. Skuteczne przeciwdziałanie uzależnieniom polega nie tylko na utrzymywaniu abstynencji, ale dążeniu do poznania i wyeliminowania czynników, które powodują uzależnienia. Jest to możliwe w ramach pogłębionej psychoterapii.</p>
    </div>
    <div class="oferta-subpages_photo">
      <img src="/assets/addiction.jpg" alt="Pomoc w uzależnieniach">
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="oferta-subpages">
      <div class="oferta-subpages__people">
        <div class="section-titles">
          <h3>terapeuci:</h3>
          <hr/>
        </div>
        <%= link_to zespol_donata_grodek_path do %>
          <h4><i class="fas fa-chevron-right"></i>Donata Grodek</h4>
        <%end%>
        <%= link_to zespol_grzegorz_szczeblewski_path do %>
          <h4><i class="fas fa-chevron-right"></i>Grzegorz Szczeblewski</h4>
        <%end%>
        <%= link_to zespol_elzbieta_walczak_path do %>
          <h4><i class="fas fa-chevron-right"></i>Elżbieta Walczak</h4>
        <%end%>
        <%= link_to zespol_dominika_lisiecka_path do %>
          <h4><i class="fas fa-chevron-right"></i>Dominika Lisiecka</h4>
        <%end%>
      </div>

      <div class="oferta-subpages__contact text-center">
        <%= render 'shared/kontakt-box' %>
      </div>
    </div>
  </div>
</section>

app/views/reviews/index.html.erb
<% if user_signed_in? %>
  <section>
    <div class="container">
      <div class="section-titles">
        <h1>Opinie Klientów</h1>
        <hr>
      </div>

      <div class="reviews-buttons">
        <%= link_to "DODAJ OPINIE", new_review_path, class: "btn-cards" %>
      </div>

      <div class="review-list">
            <% @reviews.each do |review| %>
            <div class="review-card">
             <%= review.content %>
          <div class="show-links">
            <%= link_to 'Zmien', edit_review_path(review), class: "btn btn-primary" %>
            <%= link_to 'Usun', review_path(review), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
      </div>
        <% end %>
    </div>
  </section>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-column container">
    <div class="footer-menu">
      <h2>GABINET POMOCY PSYCHOLOGICZNEJ<br>I PSYCHOTERAPII</h2>
      <ul>
        <li><%= link_to "Psychoterpia Indywidualna", oferta_path %></li>
        <li><%= link_to "Konsultacja Psychologiczna", oferta_path %></li>
        <li><%= link_to "Pomoc Kryzysowa", oferta_path %></li>
        <li><%= link_to "Terapia Par", oferta_path %></li>
        <li><%= link_to "Pomoc w uzależnieniach", oferta_path %></li>
      </ul>
    </div>
    <div class="footer-contact footer-menu">
      <h2>KONTAKT</h2>
      <p><a href="tel://+48663061717"><i class="fas fa-phone-alt"></i> +48663061717</a></p>
      <p><a href="mailto:gabinet@psycho-terapeutyczny.pl"><i class="far fa-envelope"></i> gabinet@psycho-terapeutyczny.pl</a></p>
      <p><a href="https://goo.gl/maps/dHAgUrewkDeaVZkb8"><i class="fas fa-map-marker-alt"></i> Znajdź nas</a></p>
      <p><a href="https://www.facebook.com/CentrumPsychoterapiiKoszalin" target="_blank"><i class="fab fa-facebook"></i> Facebook</a></p>
    </div>

    <div class="footer-menu">
      <h2>MENU</h2>
      <ul>
        <li><%= link_to "Nasz zespół", zespol_path %></li>
        <li><%= link_to "Oferta", oferta_path %></li>
        <li><%= link_to "Umów wizytę", kontakt_path %></li>
        <li><%= link_to "Wynajem gabinetów", gabinety_path %></li>
      </ul>
    </div>
    <% if user_signed_in? %>
      <div class="footer-menu">
        <ul>
          <li><%= link_to "Admin", admin_path %></li>
          <li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %> </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="navbar-header container <%= yield(:navbar_class) %>">
  <%= link_to root_path, class: "site-logo-white" do %>
    <%= image_tag 'logo-white.png' %>
  <% end %>
  <%= link_to root_path, class: "site-logo" do %>
    <%= image_tag 'logo-new.png' %>
  <% end %>
  <nav>
    <ul class="nav__list">
      <li><%= link_to "nasz zespół", zespol_path, class: "nav__link" %></li>
      <li><%= link_to "oferta", oferta_path, class: "nav__link" %>
      <li><%= link_to "kontakt", kontakt_path, class: "nav__link" %></li>
      <li><%= link_to "wynajem gabinetów", gabinety_path, class: "nav__link" %></li>
      <li><a class="nav__link nav-socials" href="tel://+48663061717"><i class="fas fa-phone-alt"></i></a></li>
      <li><a class="nav__link nav-socials" href="https://www.facebook.com/CentrumPsychoterapiiKoszalin" target="_blank"><i class="fab fa-facebook"></i></a></li>
      <!-- <li class=nav__list-btn><%= link_to "rezerwacja online", href="https://www.znanylekarz.pl/grzegorz-szczeblewski/psycholog-psychoterapeuta-terapeuta/koszalin", class: "nav__link--btn" %></li> -->
    </ul>
  </nav>
  <a href="#" class="toggle-button">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
  </a>
</header>